name: Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
            node-version: 12.x
      - name: Install dependencies
        run: |
            npm install
            npm install -g truffle
            npm install -g @graphprotocol/graph-cli
      - name: Run build
        run: |
            node build.js
            graph build
        env: 
            IDEAMARKET_CLONE_TOKEN: ${{ secrets.IDEAMARKET_CLONE_TOKEN }}